### ISSUE TITLE
Build on jitpack.io not successful

### ISSUE THREAD

**Issue by DelError** [igdb/api-java#1]
Version 1.0 and 1.1 are available on jitpack.io but their builds were not completed successfully.
As a result, it is not possible to use jitpack.io as a dependency source for the library at the moment.

Issues can be seen in logs:
[Version 1.0](https://jitpack.io/com/github/igdb/api-java/1.0/build.log)
[Version 1.1](https://jitpack.io/com/github/igdb/api-java/1.1/build.log)

**Comment by husnjak** [comment]
This should work now
I have rebuilt this wrapper and tested it using jitpack and it seems to be working.

Can you try this as well?
